#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# Run from the repo root so ./gradlew, ./build.sh and local.properties resolve.
cd "$(dirname "$0")/.."

# sdk.dir lives in local.properties (gitignored), which Gradle reads directly.
ENV_FILE="local.properties"
DEFAULT_SDK_DIR="/opt/android-sdk"   # the location docs/BUILD.md recommends
PROFILE="$HOME/.profile"
PROFILE_BEGIN="# >>> loop-habit-tracker: Android SDK >>>"
PROFILE_END="# <<< loop-habit-tracker: Android SDK <<<"
VERIFY_LOG="build/setup-verify.log"

# bail "msg" stops the wizard when a required step can't be completed.
bail() {
  warn "$1"
  note "Nothing is lost: re-run scripts/setup-dev-env.sh and finished stages are skipped."
  exit 1
}

have_jdk17() { compgen -G '/usr/lib/jvm/java-17-openjdk*/bin/javac' >/dev/null; }

banner "Loop Habit Tracker: local build & test environment"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "JDK 17"
say "The Gradle toolchain compiles Loop with JDK 17; newer JDKs are untested."
if have_jdk17; then
  say "${GREEN}✓${RESET} JDK 17 is already installed."
else
  step "This installs openjdk-17-jdk-headless from Ubuntu's archive (asks for your sudo password)."
  if confirm "Install JDK 17 now?"; then
    sudo apt-get update
    sudo apt-get install -y openjdk-17-jdk-headless
    have_jdk17 || bail "JDK 17 still not found under /usr/lib/jvm."
    say "${GREEN}✓${RESET} JDK 17 installed."
  else
    bail "JDK 17 is required for everything that follows."
  fi
fi
pause

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Android command-line tools"
current_sdk=$(_existing sdk.dir || true)
default_sdk="${current_sdk:-${ANDROID_HOME:-$DEFAULT_SDK_DIR}}"
printf '  %sWhere should the Android SDK live?%s %s[Enter = %s]%s ' "$BOLD" "$RESET" "$DIM" "$default_sdk" "$RESET"
read -r SDK_DIR || true
SDK_DIR="${SDK_DIR:-$default_sdk}"
SDKMANAGER="$SDK_DIR/cmdline-tools/latest/bin/sdkmanager"

if [[ -x "$SDKMANAGER" ]]; then
  say "${GREEN}✓${RESET} Command-line tools already present in $SDK_DIR."
else
  open_url "https://developer.android.com/studio#command-line-tools-only"
  step "Scroll to 'Command line tools only' and click the Linux package (commandlinetools-linux-…_latest.zip)."
  step "Read the terms, tick the box to agree, then right-click the Download button and copy the link."
  note "Any link shaped like https://dl.google.com/android/repository/commandlinetools-linux-<number>_latest.zip works."
  ask CMDLINE_TOOLS_URL "Paste the download link:"
  [[ "$CMDLINE_TOOLS_URL" =~ ^https://dl\.google\.com/android/repository/commandlinetools-linux-[0-9]+_latest\.zip$ ]] \
    || bail "That doesn't look like the Linux command-line tools link."

  if ! mkdir -p "$SDK_DIR" 2>/dev/null || [[ ! -w "$SDK_DIR" ]]; then
    confirm "Create $SDK_DIR with sudo and make $USER its owner?" || bail "The SDK needs a directory you can write to."
    sudo mkdir -p "$SDK_DIR"
    sudo chown "$USER:" "$SDK_DIR"
  fi

  tmp=$(mktemp -d)
  say "Downloading…"
  curl -fL --progress-bar -o "$tmp/tools.zip" "$CMDLINE_TOOLS_URL" || bail "Download failed."
  unzip -q "$tmp/tools.zip" -d "$tmp"
  mkdir -p "$SDK_DIR/cmdline-tools"
  rm -rf "$SDK_DIR/cmdline-tools/latest"
  mv "$tmp/cmdline-tools" "$SDK_DIR/cmdline-tools/latest"
  rm -rf "$tmp"
  [[ -x "$SDKMANAGER" ]] || bail "sdkmanager not found after extracting."
  say "${GREEN}✓${RESET} Command-line tools installed in $SDK_DIR."
fi
pause

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Point the tools at the SDK"
say "Gradle reads sdk.dir from local.properties; build.sh and your shell read ANDROID_HOME."
git check-ignore -q "$ENV_FILE" || bail "$ENV_FILE is not gitignored; refusing to write a machine-specific path into the repo."
write_env sdk.dir "$SDK_DIR"

tmp=$(mktemp)
if [[ -f "$PROFILE" ]]; then
  sed "/^${PROFILE_BEGIN}\$/,/^${PROFILE_END}\$/d" "$PROFILE" > "$tmp"
fi
cat >> "$tmp" <<PROFILE_BLOCK
$PROFILE_BEGIN
export ANDROID_HOME="$SDK_DIR"
export PATH="\$PATH:\$ANDROID_HOME/cmdline-tools/latest/bin:\$ANDROID_HOME/platform-tools:\$ANDROID_HOME/emulator"
$PROFILE_END
PROFILE_BLOCK
mv "$tmp" "$PROFILE"
printf '  %s✓ wrote%s ANDROID_HOME and PATH → %s\n' "$GREEN" "$RESET" "$PROFILE"
export ANDROID_HOME="$SDK_DIR"
export PATH="$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator"
pause

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Android SDK licences"
say "Google asks you to accept the SDK licences yourself."
step "Read each licence and answer y to accept. Already-accepted licences are skipped."
pause "Ready to review them?"
"$SDKMANAGER" --licenses || bail "The licences weren't accepted; Gradle can't install SDK packages without them."
pause

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "SDK packages"
if [[ -x "$SDK_DIR/platform-tools/adb" && -d "$SDK_DIR/platforms/android-36" ]]; then
  say "${GREEN}✓${RESET} platform-tools and Android 36 platform already installed."
else
  say "Installing platform-tools and the Android 36 platform (compileSdk 36)."
  note "Gradle fetches the matching build-tools itself during the first build."
  "$SDKMANAGER" --install "platform-tools" "platforms;android-36" || bail "sdkmanager failed."
  say "${GREEN}✓${RESET} SDK packages installed."
fi
pause

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Build and unit tests"
say "Builds the debug APK and runs the unit tests (core JVM tests include the Calendar image tests)."
note "The first run downloads Gradle and every dependency, so expect 10–20 minutes."
pause "Start the build?"
mkdir -p build
set +e
./gradlew --console=plain --continue \
  :uhabits-android:assembleDebug :uhabits-core:jvmTest :uhabits-android:testDebugUnitTest 2>&1 | tee "$VERIFY_LOG"
gradle_status=${PIPESTATUS[0]}
set -e

_clear
if (( gradle_status == 0 )); then
  RESULT="BUILD SUCCESSFUL: debug APK built, all unit tests passed."
  say "${GREEN}✓${RESET} $RESULT"
else
  RESULT="BUILD FAILED: see the failures below."
  warn "$RESULT"
fi
FAILURES=$(grep -E ' FAILED$|^\* What went wrong:' -A2 "$VERIFY_LOG" | grep -vE '^--$' | head -40 || true)
[[ -n "$FAILURES" ]] && printf '%s\n' "$FAILURES" | sed 's/^/    /'
note "Full log: $VERIFY_LOG"

if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  if confirm "Post this result as a comment on issue #2 (its acceptance criteria ask for it)?"; then
    {
      printf 'Environment verified with `scripts/setup-dev-env.sh` on %s (%s, %s).\n\n' \
        "$(date +%Y-%m-%d)" "$(. /etc/os-release && echo "$PRETTY_NAME")" "$(uname -m)"
      printf '**%s**\n\n' "$RESULT"
      printf 'Command: `./gradlew --continue :uhabits-android:assembleDebug :uhabits-core:jvmTest :uhabits-android:testDebugUnitTest`\n'
      if [[ -n "$FAILURES" ]]; then
        printf '\nFailures on unmodified `%s`:\n\n```\n%s\n```\n' "$(git rev-parse --short HEAD)" "$FAILURES"
      fi
    } | gh issue comment 2 --body-file - >/dev/null \
      && printf '  %s✓ posted%s result on issue #2\n' "$GREEN" "$RESET" \
      || SKIPPED+=("comment the build result on issue #2")
  fi
else
  SKIPPED+=("comment the build result on issue #2 (gh not ready)")
fi
pause

# ── Stage 7 ───────────────────────────────────────────────────────────────
stage "Emulator (optional)"
say "Only needed to run the Android view tests and accept their reference images."
say "Agents don't need it; you can add it later by re-running this wizard."
if confirm "Set up an emulator now?"; then
  if ! command -v ts >/dev/null 2>&1; then
    confirm "build.sh needs 'ts' from moreutils. Install it with sudo apt-get?" \
      || bail "build.sh can't run without moreutils."
    sudo apt-get install -y moreutils
  fi

  if ! id -nG | grep -qw kvm; then
    if getent group kvm | cut -d: -f4 | tr ',' '\n' | grep -qx "$USER"; then
      warn "You're in the kvm group, but this login session predates it."
      bail "Log out and back in, then re-run this wizard to finish the emulator."
    fi
    confirm "Add $USER to the kvm group with sudo (hardware acceleration for the x86_64 emulator)?" \
      || bail "The emulator is unusably slow without KVM access."
    sudo usermod -aG kvm "$USER"
    bail "Added to kvm. Log out and back in, then re-run this wizard to finish the emulator."
  fi

  "$SDKMANAGER" --install "emulator" || bail "sdkmanager failed to install the emulator."
  printf '  %sAndroid API level for the emulator?%s %s[Enter = 34, the newest level CI used]%s ' "$BOLD" "$RESET" "$DIM" "$RESET"
  read -r EMULATOR_API || true
  EMULATOR_API="${EMULATOR_API:-34}"
  [[ "$EMULATOR_API" =~ ^[0-9]+$ ]] || bail "API level must be a number."
  ./build.sh android-setup "$EMULATOR_API" || bail "build.sh android-setup failed."
  say "${GREEN}✓${RESET} Emulator created. Run view tests with: ./build.sh android-tests $EMULATOR_API"
else
  note "Skipped the emulator."
fi
pause

finish
note "Open a new terminal (or run: source ~/.profile) so ANDROID_HOME is on your PATH."
note "Gradle already finds the SDK through local.properties."
printf '\n'
